default_settings: null
behaviors:
  TetrisLearning:
    trainer_type: sac
    hyperparameters:
      batch_size: 512
      buffer_size: 50000
      buffer_init_steps: 0
      init_entcoef: 1.0
      learning_rate: 3.0e-4
      learning_rate_schedule: constant
    network_settings:      
      hidden_units: 128
      num_layers: 2 
    reward_signals:
        extrinsic:
            strength: 1.0
            gamma: 0.99  
    max_steps: 5.0e5    
    time_horizon: 64
    keep_checkpoints: 5
    summary_freq: 5000
env_settings:
  env_path: null
  env_args: null
  base_port: 5005
  num_envs: 1
  seed: -1
engine_settings:
  width: 84
  height: 84
  quality_level: 5
  time_scale: 20.0
  target_frame_rate: -1
  capture_frame_rate: 60
  no_graphics: false
environment_parameters: null
checkpoint_settings:
  run_id: Test38
  initialize_from: null
  load_model: false
  resume: false
  force: false
  train_model: false
  inference: false
debug: false
 