default_settings: null
behaviors: !!python/object/apply:mlagents.trainers.settings.DefaultTrainerDict
- !!python/name:mlagents.trainers.settings.TrainerSettings ''
env_settings:
  env_path: null
  env_args: null
  base_port: 5005
  num_envs: 1
  seed: -1
engine_settings:
  width: 84
  height: 84
  quality_level: 5
  time_scale: 20
  target_frame_rate: -1
  capture_frame_rate: 60
  no_graphics: false
environment_parameters: null
checkpoint_settings:
  run_id: Test46
  initialize_from: null
  load_model: false
  resume: false
  force: false
  train_model: false
  inference: false
debug: false
    trainer: sac
    batch_size: 128
    buffer_size: 50000
    buffer_init_steps: 0
    hidden_units: 128
    init_entcoef: 1.0
    learning_rate: 3.0e-4
    learning_rate_schedule: constant
    max_steps: 5.0e5
    memory_size: 128
    normalize: false
    steps_per_update: 10
    num_layers: 2
    time_horizon: 64
    sequence_length: 64
    summary_freq: 10000
    tau: 0.005
    use_recurrent: false
    vis_encode_type: simple
    reward_signals:
        extrinsic:
            strength: 1.0
            gamma: 0.99
        gail:
        strength: 0.0
        demo_path: C:\Users\39347\Documents\ml-agents\Tetris-MLAgents\Tetris 2D\Demos\TetrisDemo_18.demo
    behavioral_cloning:
      strength: 0.0
      demo_path: C:\Users\39347\Documents\ml-agents\Tetris-MLAgents\Tetris 2D\Demos\TetrisDemo_18.demo
    steps_per_update: 1
    hidden_units: 128
    batch_size: 512
    buffer_size: 50000
    buffer_init_steps: 10000
    learning_rate: 0.001
    max_steps: 1.0e7
